### ISSUE TITLE
Handle secrets elegantly

### ISSUE THREAD

**Issue by evantravers** [evantravers/dotfiles#1]
Right now, I'm using `git stash` to hide certain secrets, but I need
some kind of other system, either ansible or a shell script I think.

**Comment by jaywilliams** [comment]
What about a local, untracked .env file? Or possibly employ macOS's Keychain functionality to store credentials there?

**Comment by evantravers** [comment]
Hmm… something like that should work, I guess you are suggesting having the
.env file work with the make file to fill in any subsitutions or strings
required?

**Comment by jaywilliams** [comment]
I was either thinking of a `.env` file with environment variables for each password (easy, but not super secure, depends on the level of security you need), or using the [macOS Keychain](https://www.netmeister.org/blog/keychain-passwords.html) as your password store, and loading your secrets into your environment that way.

**Comment by evantravers** [comment]
https://github.com/StackExchange/blackbox

Sticking this in there for later…

**Comment by evantravers** [comment]
https://git-secret.io/

Saving this for later…
