### ISSUE TITLE
Curious how solargraph is working for you?

### ISSUE THREAD

**Issue by megalithic** [evantravers/dotfiles#2]
https://github.com/evantravers/dotfiles/blob/598bc69606a5f31ae26d46d8d463ddbe8e3f152b/nvim/.config/nvim/init.lua#L260-L271

**Comment by evantravers** [comment]
Up and down.

I can't quite figure out what makes it work and what doesn't. At least on my blog…

![image](https://user-images.githubusercontent.com/62209/109032016-e5543e80-768a-11eb-8faa-35f51c898e4c.png)

I get errors… but some of them are gems that I kind of wish it could see.

![image](https://user-images.githubusercontent.com/62209/109032120-fac96880-768a-11eb-902e-7d18ee0bf1e6.png)

I can see omnicomplete and signature help… but sometime's it's lagged as `solargraph` figures out the universe.
